version: '3.4'

services:
  osx:
    container_name: PodMan-osx
    build:
      context: .
      args:
        - SIZE=200G
        - VERSION=10.15.5
    image: bphd/PodMan-osx
    privileged: true
    environment:
      - DISPLAY=${DISPLAY:-:0.0}
    network_mode: "host"
    cap_add:
      - ALL
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
      - /lib/modules:/lib/modules
      - PodMan-osx_data:/home

volumes:
  PodMan-osx_data:
    name: PodMan-osx_data
